"""
SARC_MODE=scraping SARC_CONFIG=secrets/sarc-client-distant.yaml uv run fixes/get_metrics_by_month.py --start 2026-01-01 --end 2026-04-15 --output-dir reports/ --all

Generate one RGU*seconds report per calendar month in [--start, --end].

Each monthly window is clipped to [--start, --end] at the edges, so partial
months at the boundaries are honored (e.g. --start 2026-04-15 yields an
April window of 15-30 only).

The output filename for each month is generated by
`fixes.get_metrics._default_output_path`, which encodes the exact window
in UTC. Re-running the script with the same bounds produces the same
filenames and skips months whose report already exists and is non-empty.
"""

import argparse
import logging
import sys
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path

from fixes.get_metrics import _default_output_path, show_metrics

logger = logging.getLogger("sarc-metrics-by-month")


def _iter_months(start: datetime, end: datetime) -> Iterator[tuple[datetime, datetime]]:
    """
    Yield (window_start, window_end) tuples, one per calendar month that
    intersects [start, end]. Windows are clipped to [start, end] at the edges.

    Both `start` and `end` must be timezone-aware and in the same timezone;
    month boundaries are computed in that timezone.
    """
    current = start.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    while current < end:
        if current.month == 12:
            next_start = current.replace(year=current.year + 1, month=1)
        else:
            next_start = current.replace(month=current.month + 1)

        window_start = max(current, start)
        window_end = min(next_start, end)

        yield window_start, window_end
        current = next_start


def main() -> None:
    logging.basicConfig(level=logging.ERROR, force=True)

    parser = argparse.ArgumentParser()
    parser.add_argument("-s", "--start", type=str, required=True)
    parser.add_argument("-e", "--end", type=str, required=True)
    parser.add_argument(
        "-O", "--output-dir", type=str, required=True, help="Directory for reports"
    )
    parser.add_argument("-a", "--all", action="store_true", help="Show all metrics")
    parser.add_argument(
        "-t", "--total", action="store_true", help="Show metrics for total"
    )
    parser.add_argument(
        "-d",
        "--cluster-type",
        action="store_true",
        help="Show metrics per cluster type",
    )
    parser.add_argument(
        "-c", "--cluster", action="store_true", help="Show metrics per cluster"
    )

    args = parser.parse_args()

    # Parse inputs in the user's local timezone so that month boundaries
    # match the user's intuition ("April" = April 1 local, not April 1 UTC).
    time_from_local = datetime.fromisoformat(args.start).astimezone()
    time_to_local = datetime.fromisoformat(args.end).astimezone()

    if time_from_local > time_to_local:
        print(
            "Expected time_from <= time_to",
            time_from_local,
            time_to_local,
            file=sys.stderr,
        )
        sys.exit(1)

    per_total = args.all or args.total
    per_cluster_type = args.all or args.cluster_type
    per_cluster = args.all or args.cluster

    if not per_total and not per_cluster_type and not per_cluster:
        print(
            "No metrics required, nothing to do. Pass either --all, --total, --cluster-type or --cluster."
        )
        sys.exit(1)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    for window_start_local, window_end_local in _iter_months(
        time_from_local, time_to_local
    ):
        # Convert to UTC before calling show_metrics, to match get_metrics.py.
        window_start = window_start_local.astimezone(UTC)
        window_end = window_end_local.astimezone(UTC)

        filename = _default_output_path(
            window_start, window_end, per_total, per_cluster_type, per_cluster
        )
        path = output_dir / filename

        if path.exists() and path.stat().st_size > 0:
            logger.info(
                f"[skip] {path} already exists and is non-empty ({path.stat().st_size} bytes)."
            )
            continue

        logger.info(
            f"[generate] {path} for window {window_start.isoformat()} -> {window_end.isoformat()}"
        )
        show_metrics(
            window_start,
            window_end,
            per_total=per_total,
            per_cluster_type=per_cluster_type,
            per_cluster=per_cluster,
            output=str(path),
        )


if __name__ == "__main__":
    main()
